### ISSUE TITLE
I get errors when I run it

### ISSUE THREAD

**Issue by tylergraf** [simpulton/ngrx-rest-app#6]
I get the header and no content.

Here are the errors:
```bash
Uncaught Error: Cannot find module "./client/vendor.ts"webpackMissingModule @ vendor.js:6(anonymous function) @ vendor.js:6__webpack_require__ @ bootstrap d1163b2b1a6ea5ae602e:50webpackJsonpCallback @ bootstrap d1163b2b1a6ea5ae602e:21(anonymous function) @ vendor.js:1
app.js:6Uncaught Error: Cannot find module "./client/bootstrap.ts"webpackMissingModule @ app.js:6(anonymous function) @ app.js:6__webpack_require__ @ bootstrap d1163b2b1a6ea5ae602e:50webpackJsonpCallback @ bootstrap d1163b2b1a6ea5ae602e:21(anonymous function) @ app.js:1
client?e36c:45 [WDS] Errors while compiling.
client?e36c:47 ./client/vendor.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/Users/tylergraf/Sites/ngrx-rest-app/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/tylergraf/Sites/ngrx-rest-app/node_modules/tslint/lib/tslint.js:24:44)
    at Object.lint (/Users/tylergraf/Sites/ngrx-rest-app/node_modules/tslint-loader/index.js:55:23)
    at Object.module.exports (/Users/tylergraf/Sites/ngrx-rest-app/node_modules/tslint-loader/index.js:139:8)
 @ multi vendoronSocketMsg.errors @ client?e36c:47sock.onmessage @ client?e36c:82EventTarget.dispatchEvent @ eventtarget.js:49(anonymous function) @ main.js:274SockJS._transportMessage @ main.js:272EventEmitter.emit @ emitter.js:44WebSocketTransport.ws.onmessage @ websocket.js:35
client?e36c:47 ./client/bootstrap.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/Users/tylergraf/Sites/ngrx-rest-app/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/tylergraf/Sites/ngrx-rest-app/node_modules/tslint/lib/tslint.js:24:44)
    at Object.lint (/Users/tylergraf/Sites/ngrx-rest-app/node_modules/tslint-loader/index.js:55:23)
    at Object.module.exports (/Users/tylergraf/Sites/ngrx-rest-app/node_modules/tslint-loader/index.js:139:8)
 @ multi app
```

**Comment by Cabarfeidh** [comment]
Any updates to this issue?
I manage to generate it too!

**Comment by matthewharwood** [comment]
Getting same errors.  :+1:

**Comment by akaztp** [comment]
Fast fix: remove the line
"no-trailing-comma": true,
from file "tslint.json".

**Comment by Cabarfeidh** [comment]
Thanks akaztp...did the job!

**Comment by simpulton** [comment]
That command was changed... Will update in the morning. Thanks!

**Comment by matthewharwood** [comment]
Thanks for the speedy response @simpulton and @akaztp ... This new paradigm is difficult and it's people like you that are really making it possible.

**Comment by simpulton** [comment]
Just pushed the fix :D
